version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
jobs:
  test-3.6: &test-template
    working_directory: ~/visidata
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/share
      - run: sudo chown -R circleci:circleci /usr/local/lib
      - run: locale
      - run:
          name: dependencies
          command: |
            pip3 install -r requirements.txt
      - run:
          command: |
            dev/test.sh
