name: visidata-ci-build
on:
  pull_request:
    branches:
      - stable
      - develop
  push:
    branches:
    - stable
    - develop

jobs:
  run-tests:

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]

    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.pythonversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Environment
      run: |
        export PYTHONPATH=~/visidata:~/visidata/visidata
        locale

    - name: Install Base VisiData
      run: pip3 install .

    - name: Ensure VisiData works with Base Dependencies
      run: vd --version

    - name: Ensure VisiData can load a dir
      run: vd . --batch

    - name: Install optional dependencies
      run: |
        pip3 install -r requirements.txt
        pip3 install pytest

    - name: Run unit tests
      run: |
        pytest -sv visidata/tests/

    - name: Run Cmdlog Tests
      run: dev/test.sh
      shell: bash

    - name: Test macros
      run: |
        mkdir -p ~/.visidata
        cp tests/macros/macro* ~/.visidata/
        vd --batch -p tests/macros/test_macro.vd --output tests/macros/golden/test_macro.tsv
        git --no-pager diff --numstat tests/
        git --no-pager diff --exit-code tests/

    - name: Check docs are built without errors
      run: |
        sudo apt install aha
        dev/mkman.sh

    - name: Ensure VisiData can create completions
      run: python -v dev/zsh-completion.py
